agent:
  value_r_lower_range:
    min: 0.25
    max: 0.5

  value_r_higher_range:
    min: 0.5 #doesnt matter
    max: 0.75

  sigma: 1
  agent_type: EllipticalExponentiallyRecurring
  init_cash:
    min: 5
    max: 50

  lambda_value:
    min: 0.01
    max: 1

seed:
  random_seed: 36
  batch_size: 32

parallel:
  number_of_threads: 8

market:
  market_duration:
    min: 50
    max: 600
  liquidity_constant:
    min: 5
    max: 100
  init_price: 0.5
  percent:
    min: 0.0001
    max: 0.05
ga:
  number_generations:
    min: 2
    max: 10

  no_of_agents_per_market:
    min: 3
    max: 7

  retain_top_k_agents_per_market:
    min: 3 # doesnt matter
    max: 15 #doesnt matter

  top_agents_n:
    min: 50
    max: 100
cv: 1

n_trials: 2500

paths:
  experiment_location: ../../data/tuning/
